FROM node:18.12.1
WORKDIR /app
COPY ["package.json", "package-lock.json*", "./"]
RUN npm install && mv node_modules ../
COPY . .
EXPOSE 3000
RUN chown -R node /app
ENV REACT_APP_SOCKET_SERVER_URL=${REACT_APP_SOCKET_SERVER_URL}
USER node
CMD ["npm", "start"]
