version: '3.9'

services:
  cache:
    image: redis/redis-stack:latest
    container_name: redis
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - rediscache:/data
    networks:
      - fleetnet
  
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodata:/data/db
    networks:
      - fleetnet
  
  postgres:
    image: postgres:13-alpine
    restart: always
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=fleetdb
    ports:
      - 5432:5432
    networks:
      - fleetnet
    volumes:
      - pgdata:/var/lib/postgresql/data

  rest-service:
    build:
      context: ./rest_svc
      dockerfile: Dockerfile.restsvc
    environment:
      PORT: 8090
      DATABASE_URL: "postgresql://postgres:dev@postgres:5432/fleetdb?schema=public"
      JWT_SECRET: something-secret
      REDIS_HOST: cache
      REDIS_PORT: 6379
      REDIS_PASSWORD: eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    ports:
      - 8090:8090
    networks:
      - fleetnet
    depends_on:
      - cache
      - postgres

  comm-service:
    build:
      context: ./comm_svc
      dockerfile: Dockerfile.commsvc
    environment:
      PORT: 8000
      JWT_SECRET: something-secret
      MONGO_URL: mongodb://root:root@mongo:27017
    ports:
      - 8000:8000
    networks:
      - fleetnet
    depends_on:
      - mongo
    volumes:
      - ./comm_svc/node_modules:/app/node_modules

  # client:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile.client 
  #   environment:
  #     NODE_ENV: production
  #     REACT_APP_SOCKET_SERVER_URL: http://comm-service:8000
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - fleetnet
    # depends_on:
      # - comm-service
      # - rest-service

networks:
  fleetnet:

volumes:
  mongodata:
    driver: bridge
  pgdata:
    driver: bridge
  rediscache: